appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: VyBIxOQ7u0q8KUuz5J35QYJto1GNL2EEND9hHr2HFPCetHjIR5nrh6PvWSL4JLl076+sGcpXhjsVGnxclwqPbRfl1PKBoRXUodV1pVDd7qiq/RsyF06I3weRC140dMJPy6feEz+4fyRnrKmN3GWLCF8Lc/1cOTOBHGtsSans6mvBQwQY+YmF5jbZQeirc7fD0ZDFUQOMZGHbKiylw2NKRlJwLuiQnAWYImJhlTvSf6GLjU9jkfY8+062erv2MLfd7wDSOMV0PpmgR0RKwsxpXyS9P56OZiFnapHhf6+YKH0kmYrxuWQMcU+OP1o+zadnQAL43pbW+8KlzWqZ6SHj2OhkYpLovyo/6tK2o49HKDef1o7UHrox/K41JOMTwdQVlfqGmlN5WaLWJJ2EZcRCVZoFyjC+Skd7N405u4hCY4l821IP4zVcM3lorYrJttC96MpwarTf7TCKEHfSKClL+k+WVQGp3/hYHZwpov7ev1sA4TbhPb1Z71vqhwbJRGPNHnhEXlH+iS32xvybknjQXCV8YUojyO+Ez2l/adtH2wZCmK2hOD6T/nb0irgQfLdTc1/dPfHPukpzLxntjEcqJ1ziycVANi1JOG6tC54DoooNnrcpKJGBs1SNE+OHqz5P5TltWCz5+IY2ZeXRpIku+nKV/e57sQbFAC84CWYR4lk=}
provider: {linux_aarch64: default, linux_ppc64le: default}
